/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a carbon audit */
        post: operations["audit_api_audit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare two audits */
        post: operations["compare_api_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/methodology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Carbon model constants, thresholds and ML model details */
        get: operations["methodology_api_methodology_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssetInfo */
        AssetInfo: {
            /** Name */
            name: string;
            /** Url */
            url: string;
            /**
             * Asset Type
             * @enum {string}
             */
            asset_type: "image" | "script" | "css" | "font" | "media" | "other";
            /** Size Bytes */
            size_bytes: number;
            /** Co2 Grams */
            co2_grams: number;
            /**
             * Status
             * @enum {string}
             */
            status: "green" | "amber" | "red";
            /** Optimization Tip */
            optimization_tip: string;
        };
        /** AuditRequest */
        AuditRequest: {
            /**
             * Url
             * Format: uri
             * @description Website to audit; https:// is assumed when no scheme is given.
             * @example python.org
             */
            url: string;
        };
        /** AuditResponse */
        AuditResponse: {
            /** Id */
            id: string;
            /** Url */
            url: string;
            /**
             * Audited At
             * Format: date-time
             */
            audited_at: string;
            /** Grade */
            grade: string;
            /** Score */
            score: number;
            /**
             * Total Co2
             * @description Grams of CO2 per page visit
             */
            total_co2: number;
            /** Annual Co2 Kg */
            annual_co2_kg: number;
            /** Total Bytes */
            total_bytes: number;
            /** Request Count */
            request_count: number;
            /** Categories */
            categories: components["schemas"]["CategoryBreakdown"][];
            /** Rating */
            rating: string;
            /** Trees To Offset */
            trees_to_offset: number;
            /** Page Weight Mb */
            page_weight_mb: number;
            /** Comparison */
            comparison: string;
            /** Assets */
            assets: components["schemas"]["AssetInfo"][];
            ml_prediction: components["schemas"]["MLPrediction"];
        };
        /**
         * AuditSummary
         * @description The fields /api/compare needs; a full AuditResponse satisfies it.
         */
        AuditSummary: {
            /** Id */
            id: string;
            /** Url */
            url: string;
            /**
             * Audited At
             * Format: date-time
             */
            audited_at: string;
            /** Grade */
            grade: string;
            /** Score */
            score: number;
            /**
             * Total Co2
             * @description Grams of CO2 per page visit
             */
            total_co2: number;
            /** Annual Co2 Kg */
            annual_co2_kg: number;
            /** Total Bytes */
            total_bytes: number;
            /** Request Count */
            request_count: number;
            /** Categories */
            categories: components["schemas"]["CategoryBreakdown"][];
        };
        /** CategoryBreakdown */
        CategoryBreakdown: {
            /** Name */
            name: string;
            /** Count */
            count: number;
            /** Total Bytes */
            total_bytes: number;
            /** Total Co2 */
            total_co2: number;
            /** Percentage */
            percentage: number;
        };
        /** CompareRequest */
        CompareRequest: {
            a: components["schemas"]["AuditSummary"];
            b: components["schemas"]["AuditSummary"];
        };
        /** CompareResponse */
        CompareResponse: {
            older: components["schemas"]["CompareSide"];
            newer: components["schemas"]["CompareSide"];
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "better" | "worse" | "same";
            /** Summary */
            summary: string;
            /** Metrics */
            metrics: components["schemas"]["CompareRow"][];
            /** Categories */
            categories: components["schemas"]["CompareRow"][];
        };
        /** CompareRow */
        CompareRow: {
            /**
             * Key
             * @enum {string}
             */
            key: "score" | "total_co2" | "annual_co2_kg" | "total_bytes" | "request_count" | "category";
            /** Label */
            label: string;
            /** Older */
            older: number;
            /** Newer */
            newer: number;
            /**
             * Change Pct
             * @description Signed % change from older to newer; null when older is 0.
             */
            change_pct: number | null;
            /**
             * Direction
             * @enum {string}
             */
            direction: "up" | "down" | "same";
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "better" | "worse" | "same";
        };
        /** CompareSide */
        CompareSide: {
            /** Id */
            id: string;
            /** Url */
            url: string;
            /**
             * Audited At
             * Format: date-time
             */
            audited_at: string;
            /** Grade */
            grade: string;
            /** Score */
            score: number;
            /** Total Co2 */
            total_co2: number;
        };
        /** GradeBand */
        GradeBand: {
            /** Grade */
            grade: string;
            /**
             * Max Co2
             * @description Upper bound in grams per visit; null for the last grade.
             */
            max_co2: number | null;
            /** Score */
            score: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MLPrediction */
        MLPrediction: {
            /** Predicted Co2 Grams */
            predicted_co2_grams: number;
            /** Model Name */
            model_name: string;
            /** R2 Score */
            r2_score: number;
            /** Difference Pct */
            difference_pct?: number | null;
            /**
             * Agreement
             * @description Whether the model lands within the tolerance of the SWD figure.
             */
            agreement?: ("close" | "divergent") | null;
        };
        /** Methodology */
        Methodology: {
            /** Energy Per Gb */
            energy_per_gb: number;
            /** Carbon Intensity */
            carbon_intensity: number;
            /** Car Grams Per Km */
            car_grams_per_km: number;
            /** Monthly Visits */
            monthly_visits: number;
            /** Tree Kg Per Year */
            tree_kg_per_year: number;
            /** Grades */
            grades: components["schemas"]["GradeBand"][];
            /** Ratings */
            ratings: components["schemas"]["RatingBand"][];
            /** Asset Status */
            asset_status: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            ml_model: components["schemas"]["ModelInfo"];
        };
        /** ModelInfo */
        ModelInfo: {
            /** Model Name */
            model_name: string;
            /** R2 Score */
            r2_score: number;
            /** Mae */
            mae: number;
            /** Rmse */
            rmse: number;
            /** N Samples */
            n_samples: number;
            /** N Features */
            n_features: number;
            /** Agreement Tolerance Pct */
            agreement_tolerance_pct: number;
        };
        /** RatingBand */
        RatingBand: {
            /** Min Score */
            min_score: number;
            /** Label */
            label: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    audit_api_audit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    methodology_api_methodology_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Methodology"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
